pipeline {
    agent any
    
    tools{
        maven "MAVEN"
    }

    stages {
	
		stage("Checkout code"){
			steps
			{
				checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'b89d2732-0fa4-4a60-b067-edeb822cb833', url: 'https://git.nagarro.com/GITG00641/Java/abhiraj-gope.git']]])
				echo 'Check Out'
			}
        }
        stage('Clean') {
            steps {
                bat 'mvn -f DevOps-assignment-2/LibraryManagement/pom.xml clean'
                echo 'Cleaning..'
            }
        }
        stage('Compile') {
            steps {
                bat 'mvn -f DevOps-assignment-2/LibraryManagement/pom.xml compile'
                echo 'Compiling..'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn -f DevOps-assignment-2/LibraryManagement/pom.xml test'
                echo 'Testing..'
            }
        }
        stage('Packaging') {
            steps {
                bat 'mvn -f DevOps-assignment-2/LibraryManagement/pom.xml package'
                echo 'Packageing..'
            }
        }
        stage('Install') {
            steps {
                bat 'mvn -f DevOps-assignment-2/LibraryManagement/pom.xml install'
                echo 'Installing..'
            }
        }
        
      
    }
}
